version: 2

sources:
  - name: PANKAJFORSNOWFLAKE19
    description: A clone of a Postgres application database.
    database: analytics
    schema: PANKAJFORSNOWFLAKE19
    tables:
      - name: raw_customers
        description: Raw customers data.
      - name: raw_orders
        description: Raw orders data for dv.